# Generated by Django 3.2 on 2021-04-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(default=0, max_length=100)),
                ('username', models.CharField(default=0, max_length=100)),
                ('commodity', models.CharField(default=0, max_length=100)),
                ('sowing_date', models.CharField(default=0, max_length=100)),
                ('field_map', models.CharField(default=0, max_length=10000)),
                ('area', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
